trigger:
- master

pool:
  vmImage: ubuntu-latest

jobs:
- job: Sonar_SAST_Scan_Job
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - script: |
      mvn verify package sonar:sonar -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=tundewale -Dsonar.projectKey=tundewale_tundewale -Dsonar.token=811e3506d21114ff4037f3664ef7098981f4676e
    displayName: "Integrate SAST using SonarCloud to populate code coverage and secure pipeline variable in Azure DevOps DevSecOps Pipeline"
